name: deploy

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/emacommerce:${{ github.sha }}
                      ${{ secrets.DOCKERHUB_USERNAME }}/emacommerce:latest
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Imprimir el valor de sender.login
              run: |
                  echo "El usuario que hizo el push es: ${{ github.event.sender.login }}"
            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  github-token: ${{ secrets.GH_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  scope: ${{ secrets.VERCEL_ORG_ID }}
                  working-directory: ./
                  github-comment: true
                  vercel-args: '--pre'
            - name: Create issue if build fails
              if: failure()
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  ACTION_TYPE: 'Deploy'
                  URL_ACTION_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
              with:
                  assignees: ${{ github.event.sender.login }}
